# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Fix problem with vim colors inside tmux
set-option -g default-terminal "screen-256color"
set-option -a terminal-features 'alacrity:RGB'

# Start all numbering at 1 instead of 0 for better key reachability
set-option -g base-index 1
set-option -g pane-base-index 1

# Fix some neovim warnings
set-option -sg escape-time 10
set-option -g focus-events on

# Default sheel should be zsh
set-option -g default-shell /bin/zsh

# Prefix key is now alt + s
set-option -g prefix M-s

# Turn on vim like movement keys
set-window-option -g mode-keys vi

# Enter copy mode with ctrl + u
bind-key -n 'C-u' copy-mode

# Quickly open config file and reload it while inside tmux
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Needed for S-Enter to work inside a tmux session. Also, alacrity needs to map
# S-Enter to it's escape code.
set -g extended-keys always

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
# You can now seamlessly move between vim splits and tmux panes with
# ctrl + h/j/k/l keys
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Change how pane splits and new windows are handeled
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Use xclip program (you have to install it with apt) so you can copy paste # from tmux buffer to system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Increse history limit
set-option -g history-limit 100000

# makes tmux send out the proper escape codes for setting the terminal title
# This is needed to avoid having weird title after running tmuxx alias command
set-option -g set-titles on
# sets the content of the title: user@host: /current/working/directory
set-option -g set-titles-string "#(echo $USER)@#H: #{pane_current_path}"


# Installing a plugin
# Press prefix + I (capital i, as in Install) to fetch the plugin.
# Uninstalling a plugin
# Remove (or comment out) plugin from the list.
# Press prefix + alt + u (lowercase u as in uninstall) to remove the plugin.

# List of plugins
set -g @plugin 'dracula/tmux'
set -g @dracula-show-fahrenheit false
set -g @dracula-show-timezone false
set -g @dracula-border-contrast true
set -g @dracula-day-month true
set -g @dracula-show-left-icon ''

##Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


