-- Needs to be first, otherwise comments break
require("user.general_options")
require("user.keymaps")

require("user.cmp")
require("user.colorscheme")
require("user.comments")
-- require("user.lsp")
require("user.treesitter")
require("user.null-ls")
require("user.cmp")
require("user.snippets")
require("user.lualine")
require("user.null-ls")
require("user.plugins")
require("user.snippets")
require("user.treesitter")

require("user.plugins.autopairs")
require("user.plugins.gitsigns")
require("user.plugins.harpoon")
require("user.plugins.neoscroll")
require("user.plugins.nvim-tree")
require("user.plugins.telescope")
require("user.plugins.tmux")
require("user.plugins.trim")
require("user.plugins.which-key")
