require("user.general_options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.treesitter")
require("user.null-ls")
require("user.lsp")
require("user.cmp")
require("user.snippets")
require("user.lualine")
require("user.plugins.nvim-tree")
require("user.plugins.neoscroll")
require("user.plugins.gitsigns")
require("user.plugins.telescope")
require("user.plugins.tmux")
require("user.plugins.trim")
require("user.plugins.nvim-comment")
require("user.plugins.autopairs")
require("user.plugins.todo-comments")

require("transparent").setup({
	enable = false, -- boolean: enable transparent
})
